import type { Metadata } from "next";
import Header from "@/components/business/common/Header";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Header />
      <div className="w-full  bg-white">
        <div className="mx-auto max-w-7xl items-center justify-between px-6">
          {children}
        </div>
        </div>
    </>
    
  );
}
