import type { Metadata } from "next";
import { Lato } from "next/font/google";
import Header from "@/components/customer-flow/common/Header";
import Footer from "@/components/customer-flow/common/Footer";



const lato = Lato({
  subsets: ["latin"],
  weight: ["300", "400", "700", "900"],
  variable: "--font-lato",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Header />
      <div className="w-full border-b bg-white">
        <div className="mx-auto max-w-7xl items-center justify-between px-6">
            {children}
        </div>
       </div>
       <Footer />
    </>
    
  );
}
