import type { Metadata } from "next";
import { Lato } from "next/font/google";
import Header from "@/components/business/common/Header";
import "./globals.css";




const lato = Lato({
  subsets: ["latin"],
  weight: ["300", "400", "700", "900"],
  variable: "--font-lato",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${lato.variable} antialiased`}
      >

        {children}
      </body>
    </html>
  );
}
